const express = require('express')
const router = express.Router()
const { saveStory, getStories, getTopStories, updateVotes, getSingleStory } = require('../controllers/story')
const { generateStoryWithSummary } = require('../controllers/generateStoryWithSummary')
const { generateStory } = require('../middleware/generateStory')
const { storyChain } = require('../middleware/storyChain')

router.post('/save_story', saveStory) //This route is used to save a story in the database
router.post('/generate_story', generateStory, generateStoryWithSummary) // This route is used to send a request to openAI to generate a story based on a prompt provided by the user.
router.post('/chain_story', storyChain, generateStoryWithSummary) //This route is used to continue a chain story of a story previously generated by openAI.
router.get('/get_stories', getStories) //This route is used to fetch all the stories
router.get('/get_single_story', getSingleStory) //This route is used to fetch a single story
router.get('/get_top_stories', getTopStories) //This route is used to fetch top 10 stories
router.patch('/up_vote', updateVotes) //This route is used to like or unlike a story

module.exports = router


// todo
// 1. README - How to run the application, Flowchart, Challenges Faced, Improvement Areas
// 